<head>
	<title>Blue Lotus</title>
	<!-- start: META -->
	<meta charset="utf-8" />
	<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- end: META -->
	<!-- start: MAIN CSS -->


	<!-- Bootstrap -->
	<!-- uikit -->
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/skins/dropify/css/dropify.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/bower_components/uikit/css/uikit.almost-flat.min.css" media="all">
	<!-- flag icons -->
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/icons/flags/flags.min.css" media="all">
	<!-- altair admin -->
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/main.min.css" media="all">
	<link rel="stylesheet" href="<?php echo base_url();?>public/bower_components/kendo-ui/styles/kendo.common-material.min.css"/>
	<link rel="stylesheet" href="<?php echo base_url();?>public/bower_components/kendo-ui/styles/kendo.material.min.css"/>
		<!-- uikit -->
	<link rel="stylesheet" href="<?php echo base_url(); ?>public/alertas/css/sweetalert.css">

</head>

