 

<!-- common functions -->
<script src="<?php echo base_url();?>public/assets/js/common.min.js"></script>
<!-- uikit functions -->
<script src="<?php echo base_url();?>public/assets/js/uikit_custom.min.js"></script>
<!-- altair common functions/helpers -->
<script src="<?php echo base_url();?>public/assets/js/altair_admin_common.min.js"></script>

<!-- page specific plugins -->
<!-- datatables -->
<!--  dropify -->
<script src="<?php echo base_url();?>public/assets/js/custom/dropify/dist/js/dropify.min.js"></script>

<!--  form file input functions -->
<script src="<?php echo base_url();?>public/assets/js/pages/forms_file_input.min.js"></script>
<script src="<?php echo base_url();?>public/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
<!-- datatables colVis-->
<script src="<?php echo base_url();?>public/bower_components/datatables-colvis/js/dataTables.colVis.js"></script>
<!-- datatables tableTools-->
<script src="<?php echo base_url();?>public/bower_components/datatables-tabletools/js/dataTables.tableTools.js"></script>
<!-- datatables custom integration -->
<script src="<?php echo base_url();?>public/assets/js/custom/datatables_uikit.min.js"></script>

<!--  datatables functions -->
<script src="<?php echo base_url();?>public/assets/js/pages/plugins_datatables.min.js"></script>

<script src="<?php echo base_url();?>public/assets/js/pages/ecommerce_product_edit.min.js"></script>

<!-- kendo UI -->
<script src="<?php echo base_url();?>public/assets/js/kendoui_custom.min.js"></script>

<!--  kendoui functions -->
<script src="<?php echo base_url();?>public/assets/js/pages/kendoui.min.js"></script>

<script src="<?php echo base_url();?>public/assets/js/pages/page_user_edit.min.js"></script>

<script src="<?php echo base_url();?>public/assets/js/pages/page_contact_list.min.js"></script>
<script src="<?php echo base_url(); ?>public/alertas/js/sweetalert.min.js"></script>
<script src="<?php echo base_url(); ?>public/alertas/js/functions.js"></script>